// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package io.siddhi.extension.map.protobuf.autogenerated;

public interface MessageWithUnderscoreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageWithUnderscore)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string string_value = 1;</code>
   */
  String getStringValue();
  /**
   * <code>string string_value = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>int32 int_value = 2;</code>
   */
  int getIntValue();

  /**
   * <code>double doubleValue_ = 3;</code>
   */
  double getDoubleValue();
}
