// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package io.siddhi.extension.map.protobuf.autogenerated;

public interface NestedMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NestedMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringValue = 1;</code>
   */
  String getStringValue();
  /**
   * <code>string stringValue = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>int32 intValue = 2;</code>
   */
  int getIntValue();

  /**
   * <code>repeated string stringList = 3;</code>
   */
  java.util.List<String>
      getStringListList();
  /**
   * <code>repeated string stringList = 3;</code>
   */
  int getStringListCount();
  /**
   * <code>repeated string stringList = 3;</code>
   */
  String getStringList(int index);
  /**
   * <code>repeated string stringList = 3;</code>
   */
  com.google.protobuf.ByteString
      getStringListBytes(int index);
}
