// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package io.siddhi.extension.map.protobuf.autogenerated;

/**
 * Protobuf type {@code NestedMessage}
 */
public  final class NestedMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NestedMessage)
    NestedMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NestedMessage.newBuilder() to construct.
  private NestedMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NestedMessage() {
    stringValue_ = "";
    innerList_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NestedMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            stringValue_ = s;
            break;
          }
          case 16: {

            intValue_ = input.readInt32();
            break;
          }
          case 26: {
            Inner.Builder subBuilder = null;
            if (innerObject_ != null) {
              subBuilder = innerObject_.toBuilder();
            }
            innerObject_ = input.readMessage(Inner.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(innerObject_);
              innerObject_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              innerList_ = new java.util.ArrayList<Inner>();
              mutable_bitField0_ |= 0x00000008;
            }
            innerList_.add(
                input.readMessage(Inner.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        innerList_ = java.util.Collections.unmodifiableList(innerList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Sample.internal_static_NestedMessage_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Sample.internal_static_NestedMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NestedMessage.class, Builder.class);
  }

  public interface InnerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NestedMessage.Inner)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string innerString = 1;</code>
     */
    String getInnerString();
    /**
     * <code>string innerString = 1;</code>
     */
    com.google.protobuf.ByteString
        getInnerStringBytes();

    /**
     * <code>int32 innerInt = 2;</code>
     */
    int getInnerInt();
  }
  /**
   * Protobuf type {@code NestedMessage.Inner}
   */
  public  static final class Inner extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NestedMessage.Inner)
      InnerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Inner.newBuilder() to construct.
    private Inner(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Inner() {
      innerString_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Inner(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              innerString_ = s;
              break;
            }
            case 16: {

              innerInt_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Sample.internal_static_NestedMessage_Inner_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Sample.internal_static_NestedMessage_Inner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Inner.class, Builder.class);
    }

    public static final int INNERSTRING_FIELD_NUMBER = 1;
    private volatile Object innerString_;
    /**
     * <code>string innerString = 1;</code>
     */
    public String getInnerString() {
      Object ref = innerString_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        innerString_ = s;
        return s;
      }
    }
    /**
     * <code>string innerString = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInnerStringBytes() {
      Object ref = innerString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        innerString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INNERINT_FIELD_NUMBER = 2;
    private int innerInt_;
    /**
     * <code>int32 innerInt = 2;</code>
     */
    public int getInnerInt() {
      return innerInt_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getInnerStringBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, innerString_);
      }
      if (innerInt_ != 0) {
        output.writeInt32(2, innerInt_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getInnerStringBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, innerString_);
      }
      if (innerInt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, innerInt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Inner)) {
        return super.equals(obj);
      }
      Inner other = (Inner) obj;

      if (!getInnerString()
          .equals(other.getInnerString())) return false;
      if (getInnerInt()
          != other.getInnerInt()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INNERSTRING_FIELD_NUMBER;
      hash = (53 * hash) + getInnerString().hashCode();
      hash = (37 * hash) + INNERINT_FIELD_NUMBER;
      hash = (53 * hash) + getInnerInt();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Inner parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Inner parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Inner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Inner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Inner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Inner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Inner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Inner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Inner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Inner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Inner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Inner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Inner prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NestedMessage.Inner}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NestedMessage.Inner)
        InnerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Sample.internal_static_NestedMessage_Inner_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Sample.internal_static_NestedMessage_Inner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Inner.class, Builder.class);
      }

      // Construct using io.siddhi.extension.map.protobuf.autogenerated.NestedMessage.Inner.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        innerString_ = "";

        innerInt_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Sample.internal_static_NestedMessage_Inner_descriptor;
      }

      @Override
      public Inner getDefaultInstanceForType() {
        return Inner.getDefaultInstance();
      }

      @Override
      public Inner build() {
        Inner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Inner buildPartial() {
        Inner result = new Inner(this);
        result.innerString_ = innerString_;
        result.innerInt_ = innerInt_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Inner) {
          return mergeFrom((Inner)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Inner other) {
        if (other == Inner.getDefaultInstance()) return this;
        if (!other.getInnerString().isEmpty()) {
          innerString_ = other.innerString_;
          onChanged();
        }
        if (other.getInnerInt() != 0) {
          setInnerInt(other.getInnerInt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Inner parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Inner) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object innerString_ = "";
      /**
       * <code>string innerString = 1;</code>
       */
      public String getInnerString() {
        Object ref = innerString_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          innerString_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string innerString = 1;</code>
       */
      public com.google.protobuf.ByteString
          getInnerStringBytes() {
        Object ref = innerString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          innerString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string innerString = 1;</code>
       */
      public Builder setInnerString(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        innerString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string innerString = 1;</code>
       */
      public Builder clearInnerString() {
        
        innerString_ = getDefaultInstance().getInnerString();
        onChanged();
        return this;
      }
      /**
       * <code>string innerString = 1;</code>
       */
      public Builder setInnerStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        innerString_ = value;
        onChanged();
        return this;
      }

      private int innerInt_ ;
      /**
       * <code>int32 innerInt = 2;</code>
       */
      public int getInnerInt() {
        return innerInt_;
      }
      /**
       * <code>int32 innerInt = 2;</code>
       */
      public Builder setInnerInt(int value) {
        
        innerInt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 innerInt = 2;</code>
       */
      public Builder clearInnerInt() {
        
        innerInt_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NestedMessage.Inner)
    }

    // @@protoc_insertion_point(class_scope:NestedMessage.Inner)
    private static final Inner DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Inner();
    }

    public static Inner getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Inner>
        PARSER = new com.google.protobuf.AbstractParser<Inner>() {
      @Override
      public Inner parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Inner(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Inner> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Inner> getParserForType() {
      return PARSER;
    }

    @Override
    public Inner getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int STRINGVALUE_FIELD_NUMBER = 1;
  private volatile Object stringValue_;
  /**
   * <code>string stringValue = 1;</code>
   */
  public String getStringValue() {
    Object ref = stringValue_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      stringValue_ = s;
      return s;
    }
  }
  /**
   * <code>string stringValue = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStringValueBytes() {
    Object ref = stringValue_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      stringValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTVALUE_FIELD_NUMBER = 2;
  private int intValue_;
  /**
   * <code>int32 intValue = 2;</code>
   */
  public int getIntValue() {
    return intValue_;
  }

  public static final int INNEROBJECT_FIELD_NUMBER = 3;
  private Inner innerObject_;
  /**
   * <code>.NestedMessage.Inner innerObject = 3;</code>
   */
  public boolean hasInnerObject() {
    return innerObject_ != null;
  }
  /**
   * <code>.NestedMessage.Inner innerObject = 3;</code>
   */
  public Inner getInnerObject() {
    return innerObject_ == null ? Inner.getDefaultInstance() : innerObject_;
  }
  /**
   * <code>.NestedMessage.Inner innerObject = 3;</code>
   */
  public InnerOrBuilder getInnerObjectOrBuilder() {
    return getInnerObject();
  }

  public static final int INNERLIST_FIELD_NUMBER = 4;
  private java.util.List<Inner> innerList_;
  /**
   * <code>repeated .NestedMessage.Inner innerList = 4;</code>
   */
  public java.util.List<Inner> getInnerListList() {
    return innerList_;
  }
  /**
   * <code>repeated .NestedMessage.Inner innerList = 4;</code>
   */
  public java.util.List<? extends InnerOrBuilder>
      getInnerListOrBuilderList() {
    return innerList_;
  }
  /**
   * <code>repeated .NestedMessage.Inner innerList = 4;</code>
   */
  public int getInnerListCount() {
    return innerList_.size();
  }
  /**
   * <code>repeated .NestedMessage.Inner innerList = 4;</code>
   */
  public Inner getInnerList(int index) {
    return innerList_.get(index);
  }
  /**
   * <code>repeated .NestedMessage.Inner innerList = 4;</code>
   */
  public InnerOrBuilder getInnerListOrBuilder(
      int index) {
    return innerList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStringValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stringValue_);
    }
    if (intValue_ != 0) {
      output.writeInt32(2, intValue_);
    }
    if (innerObject_ != null) {
      output.writeMessage(3, getInnerObject());
    }
    for (int i = 0; i < innerList_.size(); i++) {
      output.writeMessage(4, innerList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStringValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stringValue_);
    }
    if (intValue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, intValue_);
    }
    if (innerObject_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getInnerObject());
    }
    for (int i = 0; i < innerList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, innerList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NestedMessage)) {
      return super.equals(obj);
    }
    NestedMessage other = (NestedMessage) obj;

    if (!getStringValue()
        .equals(other.getStringValue())) return false;
    if (getIntValue()
        != other.getIntValue()) return false;
    if (hasInnerObject() != other.hasInnerObject()) return false;
    if (hasInnerObject()) {
      if (!getInnerObject()
          .equals(other.getInnerObject())) return false;
    }
    if (!getInnerListList()
        .equals(other.getInnerListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STRINGVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getStringValue().hashCode();
    hash = (37 * hash) + INTVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getIntValue();
    if (hasInnerObject()) {
      hash = (37 * hash) + INNEROBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getInnerObject().hashCode();
    }
    if (getInnerListCount() > 0) {
      hash = (37 * hash) + INNERLIST_FIELD_NUMBER;
      hash = (53 * hash) + getInnerListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NestedMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NestedMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NestedMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NestedMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NestedMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NestedMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NestedMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NestedMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static NestedMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static NestedMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static NestedMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NestedMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NestedMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code NestedMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NestedMessage)
      NestedMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Sample.internal_static_NestedMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Sample.internal_static_NestedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NestedMessage.class, Builder.class);
    }

    // Construct using io.siddhi.extension.map.protobuf.autogenerated.NestedMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getInnerListFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      stringValue_ = "";

      intValue_ = 0;

      if (innerObjectBuilder_ == null) {
        innerObject_ = null;
      } else {
        innerObject_ = null;
        innerObjectBuilder_ = null;
      }
      if (innerListBuilder_ == null) {
        innerList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        innerListBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Sample.internal_static_NestedMessage_descriptor;
    }

    @Override
    public NestedMessage getDefaultInstanceForType() {
      return NestedMessage.getDefaultInstance();
    }

    @Override
    public NestedMessage build() {
      NestedMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public NestedMessage buildPartial() {
      NestedMessage result = new NestedMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.stringValue_ = stringValue_;
      result.intValue_ = intValue_;
      if (innerObjectBuilder_ == null) {
        result.innerObject_ = innerObject_;
      } else {
        result.innerObject_ = innerObjectBuilder_.build();
      }
      if (innerListBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          innerList_ = java.util.Collections.unmodifiableList(innerList_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.innerList_ = innerList_;
      } else {
        result.innerList_ = innerListBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NestedMessage) {
        return mergeFrom((NestedMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NestedMessage other) {
      if (other == NestedMessage.getDefaultInstance()) return this;
      if (!other.getStringValue().isEmpty()) {
        stringValue_ = other.stringValue_;
        onChanged();
      }
      if (other.getIntValue() != 0) {
        setIntValue(other.getIntValue());
      }
      if (other.hasInnerObject()) {
        mergeInnerObject(other.getInnerObject());
      }
      if (innerListBuilder_ == null) {
        if (!other.innerList_.isEmpty()) {
          if (innerList_.isEmpty()) {
            innerList_ = other.innerList_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureInnerListIsMutable();
            innerList_.addAll(other.innerList_);
          }
          onChanged();
        }
      } else {
        if (!other.innerList_.isEmpty()) {
          if (innerListBuilder_.isEmpty()) {
            innerListBuilder_.dispose();
            innerListBuilder_ = null;
            innerList_ = other.innerList_;
            bitField0_ = (bitField0_ & ~0x00000008);
            innerListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInnerListFieldBuilder() : null;
          } else {
            innerListBuilder_.addAllMessages(other.innerList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      NestedMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (NestedMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object stringValue_ = "";
    /**
     * <code>string stringValue = 1;</code>
     */
    public String getStringValue() {
      Object ref = stringValue_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        stringValue_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string stringValue = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      Object ref = stringValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stringValue = 1;</code>
     */
    public Builder setStringValue(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stringValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stringValue = 1;</code>
     */
    public Builder clearStringValue() {
      
      stringValue_ = getDefaultInstance().getStringValue();
      onChanged();
      return this;
    }
    /**
     * <code>string stringValue = 1;</code>
     */
    public Builder setStringValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stringValue_ = value;
      onChanged();
      return this;
    }

    private int intValue_ ;
    /**
     * <code>int32 intValue = 2;</code>
     */
    public int getIntValue() {
      return intValue_;
    }
    /**
     * <code>int32 intValue = 2;</code>
     */
    public Builder setIntValue(int value) {
      
      intValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 intValue = 2;</code>
     */
    public Builder clearIntValue() {
      
      intValue_ = 0;
      onChanged();
      return this;
    }

    private Inner innerObject_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Inner, Inner.Builder, InnerOrBuilder> innerObjectBuilder_;
    /**
     * <code>.NestedMessage.Inner innerObject = 3;</code>
     */
    public boolean hasInnerObject() {
      return innerObjectBuilder_ != null || innerObject_ != null;
    }
    /**
     * <code>.NestedMessage.Inner innerObject = 3;</code>
     */
    public Inner getInnerObject() {
      if (innerObjectBuilder_ == null) {
        return innerObject_ == null ? Inner.getDefaultInstance() : innerObject_;
      } else {
        return innerObjectBuilder_.getMessage();
      }
    }
    /**
     * <code>.NestedMessage.Inner innerObject = 3;</code>
     */
    public Builder setInnerObject(Inner value) {
      if (innerObjectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        innerObject_ = value;
        onChanged();
      } else {
        innerObjectBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.NestedMessage.Inner innerObject = 3;</code>
     */
    public Builder setInnerObject(
        Inner.Builder builderForValue) {
      if (innerObjectBuilder_ == null) {
        innerObject_ = builderForValue.build();
        onChanged();
      } else {
        innerObjectBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.NestedMessage.Inner innerObject = 3;</code>
     */
    public Builder mergeInnerObject(Inner value) {
      if (innerObjectBuilder_ == null) {
        if (innerObject_ != null) {
          innerObject_ =
            Inner.newBuilder(innerObject_).mergeFrom(value).buildPartial();
        } else {
          innerObject_ = value;
        }
        onChanged();
      } else {
        innerObjectBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.NestedMessage.Inner innerObject = 3;</code>
     */
    public Builder clearInnerObject() {
      if (innerObjectBuilder_ == null) {
        innerObject_ = null;
        onChanged();
      } else {
        innerObject_ = null;
        innerObjectBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.NestedMessage.Inner innerObject = 3;</code>
     */
    public Inner.Builder getInnerObjectBuilder() {
      
      onChanged();
      return getInnerObjectFieldBuilder().getBuilder();
    }
    /**
     * <code>.NestedMessage.Inner innerObject = 3;</code>
     */
    public InnerOrBuilder getInnerObjectOrBuilder() {
      if (innerObjectBuilder_ != null) {
        return innerObjectBuilder_.getMessageOrBuilder();
      } else {
        return innerObject_ == null ?
            Inner.getDefaultInstance() : innerObject_;
      }
    }
    /**
     * <code>.NestedMessage.Inner innerObject = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Inner, Inner.Builder, InnerOrBuilder>
        getInnerObjectFieldBuilder() {
      if (innerObjectBuilder_ == null) {
        innerObjectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Inner, Inner.Builder, InnerOrBuilder>(
                getInnerObject(),
                getParentForChildren(),
                isClean());
        innerObject_ = null;
      }
      return innerObjectBuilder_;
    }

    private java.util.List<Inner> innerList_ =
      java.util.Collections.emptyList();
    private void ensureInnerListIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        innerList_ = new java.util.ArrayList<Inner>(innerList_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Inner, Inner.Builder, InnerOrBuilder> innerListBuilder_;

    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public java.util.List<Inner> getInnerListList() {
      if (innerListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(innerList_);
      } else {
        return innerListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public int getInnerListCount() {
      if (innerListBuilder_ == null) {
        return innerList_.size();
      } else {
        return innerListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public Inner getInnerList(int index) {
      if (innerListBuilder_ == null) {
        return innerList_.get(index);
      } else {
        return innerListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public Builder setInnerList(
        int index, Inner value) {
      if (innerListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInnerListIsMutable();
        innerList_.set(index, value);
        onChanged();
      } else {
        innerListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public Builder setInnerList(
        int index, Inner.Builder builderForValue) {
      if (innerListBuilder_ == null) {
        ensureInnerListIsMutable();
        innerList_.set(index, builderForValue.build());
        onChanged();
      } else {
        innerListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public Builder addInnerList(Inner value) {
      if (innerListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInnerListIsMutable();
        innerList_.add(value);
        onChanged();
      } else {
        innerListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public Builder addInnerList(
        int index, Inner value) {
      if (innerListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInnerListIsMutable();
        innerList_.add(index, value);
        onChanged();
      } else {
        innerListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public Builder addInnerList(
        Inner.Builder builderForValue) {
      if (innerListBuilder_ == null) {
        ensureInnerListIsMutable();
        innerList_.add(builderForValue.build());
        onChanged();
      } else {
        innerListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public Builder addInnerList(
        int index, Inner.Builder builderForValue) {
      if (innerListBuilder_ == null) {
        ensureInnerListIsMutable();
        innerList_.add(index, builderForValue.build());
        onChanged();
      } else {
        innerListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public Builder addAllInnerList(
        Iterable<? extends Inner> values) {
      if (innerListBuilder_ == null) {
        ensureInnerListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, innerList_);
        onChanged();
      } else {
        innerListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public Builder clearInnerList() {
      if (innerListBuilder_ == null) {
        innerList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        innerListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public Builder removeInnerList(int index) {
      if (innerListBuilder_ == null) {
        ensureInnerListIsMutable();
        innerList_.remove(index);
        onChanged();
      } else {
        innerListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public Inner.Builder getInnerListBuilder(
        int index) {
      return getInnerListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public InnerOrBuilder getInnerListOrBuilder(
        int index) {
      if (innerListBuilder_ == null) {
        return innerList_.get(index);  } else {
        return innerListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public java.util.List<? extends InnerOrBuilder>
         getInnerListOrBuilderList() {
      if (innerListBuilder_ != null) {
        return innerListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(innerList_);
      }
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public Inner.Builder addInnerListBuilder() {
      return getInnerListFieldBuilder().addBuilder(
          Inner.getDefaultInstance());
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public Inner.Builder addInnerListBuilder(
        int index) {
      return getInnerListFieldBuilder().addBuilder(
          index, Inner.getDefaultInstance());
    }
    /**
     * <code>repeated .NestedMessage.Inner innerList = 4;</code>
     */
    public java.util.List<Inner.Builder>
         getInnerListBuilderList() {
      return getInnerListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Inner, Inner.Builder, InnerOrBuilder>
        getInnerListFieldBuilder() {
      if (innerListBuilder_ == null) {
        innerListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Inner, Inner.Builder, InnerOrBuilder>(
                innerList_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        innerList_ = null;
      }
      return innerListBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NestedMessage)
  }

  // @@protoc_insertion_point(class_scope:NestedMessage)
  private static final NestedMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NestedMessage();
  }

  public static NestedMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NestedMessage>
      PARSER = new com.google.protobuf.AbstractParser<NestedMessage>() {
    @Override
    public NestedMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NestedMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NestedMessage> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NestedMessage> getParserForType() {
    return PARSER;
  }

  @Override
  public NestedMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

