// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package io.siddhi.extension.map.protobuf.autogenerated;

public interface OtherMessageTypesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OtherMessageTypes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Request request = 1;</code>
   */
  boolean hasRequest();
  /**
   * <code>.Request request = 1;</code>
   */
  Request getRequest();
  /**
   * <code>.Request request = 1;</code>
   */
  RequestOrBuilder getRequestOrBuilder();

  /**
   * <code>.RequestWithMap requestWithMap = 2;</code>
   */
  boolean hasRequestWithMap();
  /**
   * <code>.RequestWithMap requestWithMap = 2;</code>
   */
  RequestWithMap getRequestWithMap();
  /**
   * <code>.RequestWithMap requestWithMap = 2;</code>
   */
  RequestWithMapOrBuilder getRequestWithMapOrBuilder();

  /**
   * <code>.RequestWithList requestWithList = 3;</code>
   */
  boolean hasRequestWithList();
  /**
   * <code>.RequestWithList requestWithList = 3;</code>
   */
  RequestWithList getRequestWithList();
  /**
   * <code>.RequestWithList requestWithList = 3;</code>
   */
  RequestWithListOrBuilder getRequestWithListOrBuilder();

  /**
   * <code>repeated .Request requestList = 4;</code>
   */
  java.util.List<Request>
      getRequestListList();
  /**
   * <code>repeated .Request requestList = 4;</code>
   */
  Request getRequestList(int index);
  /**
   * <code>repeated .Request requestList = 4;</code>
   */
  int getRequestListCount();
  /**
   * <code>repeated .Request requestList = 4;</code>
   */
  java.util.List<? extends RequestOrBuilder>
      getRequestListOrBuilderList();
  /**
   * <code>repeated .Request requestList = 4;</code>
   */
  RequestOrBuilder getRequestListOrBuilder(
          int index);
}
