// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package io.siddhi.extension.map.protobuf.grpc;

/**
 * Protobuf type {@code OtherMessageTypes}
 */
public  final class OtherMessageTypes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OtherMessageTypes)
        OtherMessageTypesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OtherMessageTypes.newBuilder() to construct.
  private OtherMessageTypes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OtherMessageTypes() {
    requestList_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OtherMessageTypes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.siddhi.extension.map.protobuf.grpc.Request.Builder subBuilder = null;
            if (request_ != null) {
              subBuilder = request_.toBuilder();
            }
            request_ = input.readMessage(io.siddhi.extension.map.protobuf.grpc.Request.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(request_);
              request_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            io.siddhi.extension.map.protobuf.grpc.RequestWithMap.Builder subBuilder = null;
            if (requestWithMap_ != null) {
              subBuilder = requestWithMap_.toBuilder();
            }
            requestWithMap_ = input.readMessage(io.siddhi.extension.map.protobuf.grpc.RequestWithMap.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(requestWithMap_);
              requestWithMap_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            io.siddhi.extension.map.protobuf.grpc.RequestWithList.Builder subBuilder = null;
            if (requestWithList_ != null) {
              subBuilder = requestWithList_.toBuilder();
            }
            requestWithList_ = input.readMessage(io.siddhi.extension.map.protobuf.grpc.RequestWithList.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(requestWithList_);
              requestWithList_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              requestList_ = new java.util.ArrayList<Request>();
              mutable_bitField0_ |= 0x00000008;
            }
            requestList_.add(
                input.readMessage(io.siddhi.extension.map.protobuf.grpc.Request.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        requestList_ = java.util.Collections.unmodifiableList(requestList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.siddhi.extension.map.protobuf.grpc.Sample.internal_static_OtherMessageTypes_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.siddhi.extension.map.protobuf.grpc.Sample.internal_static_OtherMessageTypes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes.class, io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes.Builder.class);
  }

  private int bitField0_;
  public static final int REQUEST_FIELD_NUMBER = 1;
  private io.siddhi.extension.map.protobuf.grpc.Request request_;
  /**
   * <code>.Request request = 1;</code>
   */
  public boolean hasRequest() {
    return request_ != null;
  }
  /**
   * <code>.Request request = 1;</code>
   */
  public io.siddhi.extension.map.protobuf.grpc.Request getRequest() {
    return request_ == null ? io.siddhi.extension.map.protobuf.grpc.Request.getDefaultInstance() : request_;
  }
  /**
   * <code>.Request request = 1;</code>
   */
  public io.siddhi.extension.map.protobuf.grpc.RequestOrBuilder getRequestOrBuilder() {
    return getRequest();
  }

  public static final int REQUESTWITHMAP_FIELD_NUMBER = 2;
  private io.siddhi.extension.map.protobuf.grpc.RequestWithMap requestWithMap_;
  /**
   * <code>.RequestWithMap requestWithMap = 2;</code>
   */
  public boolean hasRequestWithMap() {
    return requestWithMap_ != null;
  }
  /**
   * <code>.RequestWithMap requestWithMap = 2;</code>
   */
  public io.siddhi.extension.map.protobuf.grpc.RequestWithMap getRequestWithMap() {
    return requestWithMap_ == null ? io.siddhi.extension.map.protobuf.grpc.RequestWithMap.getDefaultInstance() : requestWithMap_;
  }
  /**
   * <code>.RequestWithMap requestWithMap = 2;</code>
   */
  public io.siddhi.extension.map.protobuf.grpc.RequestWithMapOrBuilder getRequestWithMapOrBuilder() {
    return getRequestWithMap();
  }

  public static final int REQUESTWITHLIST_FIELD_NUMBER = 3;
  private io.siddhi.extension.map.protobuf.grpc.RequestWithList requestWithList_;
  /**
   * <code>.RequestWithList requestWithList = 3;</code>
   */
  public boolean hasRequestWithList() {
    return requestWithList_ != null;
  }
  /**
   * <code>.RequestWithList requestWithList = 3;</code>
   */
  public io.siddhi.extension.map.protobuf.grpc.RequestWithList getRequestWithList() {
    return requestWithList_ == null ? io.siddhi.extension.map.protobuf.grpc.RequestWithList.getDefaultInstance() : requestWithList_;
  }
  /**
   * <code>.RequestWithList requestWithList = 3;</code>
   */
  public io.siddhi.extension.map.protobuf.grpc.RequestWithListOrBuilder getRequestWithListOrBuilder() {
    return getRequestWithList();
  }

  public static final int REQUESTLIST_FIELD_NUMBER = 4;
  private java.util.List<Request> requestList_;
  /**
   * <code>repeated .Request requestList = 4;</code>
   */
  public java.util.List<Request> getRequestListList() {
    return requestList_;
  }
  /**
   * <code>repeated .Request requestList = 4;</code>
   */
  public java.util.List<? extends RequestOrBuilder>
      getRequestListOrBuilderList() {
    return requestList_;
  }
  /**
   * <code>repeated .Request requestList = 4;</code>
   */
  public int getRequestListCount() {
    return requestList_.size();
  }
  /**
   * <code>repeated .Request requestList = 4;</code>
   */
  public io.siddhi.extension.map.protobuf.grpc.Request getRequestList(int index) {
    return requestList_.get(index);
  }
  /**
   * <code>repeated .Request requestList = 4;</code>
   */
  public io.siddhi.extension.map.protobuf.grpc.RequestOrBuilder getRequestListOrBuilder(
      int index) {
    return requestList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (request_ != null) {
      output.writeMessage(1, getRequest());
    }
    if (requestWithMap_ != null) {
      output.writeMessage(2, getRequestWithMap());
    }
    if (requestWithList_ != null) {
      output.writeMessage(3, getRequestWithList());
    }
    for (int i = 0; i < requestList_.size(); i++) {
      output.writeMessage(4, requestList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (request_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRequest());
    }
    if (requestWithMap_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRequestWithMap());
    }
    if (requestWithList_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getRequestWithList());
    }
    for (int i = 0; i < requestList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, requestList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes)) {
      return super.equals(obj);
    }
    io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes other = (io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes) obj;

    if (hasRequest() != other.hasRequest()) return false;
    if (hasRequest()) {
      if (!getRequest()
          .equals(other.getRequest())) return false;
    }
    if (hasRequestWithMap() != other.hasRequestWithMap()) return false;
    if (hasRequestWithMap()) {
      if (!getRequestWithMap()
          .equals(other.getRequestWithMap())) return false;
    }
    if (hasRequestWithList() != other.hasRequestWithList()) return false;
    if (hasRequestWithList()) {
      if (!getRequestWithList()
          .equals(other.getRequestWithList())) return false;
    }
    if (!getRequestListList()
        .equals(other.getRequestListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRequest()) {
      hash = (37 * hash) + REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getRequest().hashCode();
    }
    if (hasRequestWithMap()) {
      hash = (37 * hash) + REQUESTWITHMAP_FIELD_NUMBER;
      hash = (53 * hash) + getRequestWithMap().hashCode();
    }
    if (hasRequestWithList()) {
      hash = (37 * hash) + REQUESTWITHLIST_FIELD_NUMBER;
      hash = (53 * hash) + getRequestWithList().hashCode();
    }
    if (getRequestListCount() > 0) {
      hash = (37 * hash) + REQUESTLIST_FIELD_NUMBER;
      hash = (53 * hash) + getRequestListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code OtherMessageTypes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OtherMessageTypes)
      io.siddhi.extension.map.protobuf.grpc.OtherMessageTypesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.siddhi.extension.map.protobuf.grpc.Sample.internal_static_OtherMessageTypes_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.siddhi.extension.map.protobuf.grpc.Sample.internal_static_OtherMessageTypes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes.class, io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes.Builder.class);
    }

    // Construct using io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRequestListFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (requestBuilder_ == null) {
        request_ = null;
      } else {
        request_ = null;
        requestBuilder_ = null;
      }
      if (requestWithMapBuilder_ == null) {
        requestWithMap_ = null;
      } else {
        requestWithMap_ = null;
        requestWithMapBuilder_ = null;
      }
      if (requestWithListBuilder_ == null) {
        requestWithList_ = null;
      } else {
        requestWithList_ = null;
        requestWithListBuilder_ = null;
      }
      if (requestListBuilder_ == null) {
        requestList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        requestListBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.siddhi.extension.map.protobuf.grpc.Sample.internal_static_OtherMessageTypes_descriptor;
    }

    @Override
    public io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes getDefaultInstanceForType() {
      return io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes.getDefaultInstance();
    }

    @Override
    public io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes build() {
      io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes buildPartial() {
      io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes result = new io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (requestBuilder_ == null) {
        result.request_ = request_;
      } else {
        result.request_ = requestBuilder_.build();
      }
      if (requestWithMapBuilder_ == null) {
        result.requestWithMap_ = requestWithMap_;
      } else {
        result.requestWithMap_ = requestWithMapBuilder_.build();
      }
      if (requestWithListBuilder_ == null) {
        result.requestWithList_ = requestWithList_;
      } else {
        result.requestWithList_ = requestWithListBuilder_.build();
      }
      if (requestListBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          requestList_ = java.util.Collections.unmodifiableList(requestList_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.requestList_ = requestList_;
      } else {
        result.requestList_ = requestListBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes) {
        return mergeFrom((io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes other) {
      if (other == io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes.getDefaultInstance()) return this;
      if (other.hasRequest()) {
        mergeRequest(other.getRequest());
      }
      if (other.hasRequestWithMap()) {
        mergeRequestWithMap(other.getRequestWithMap());
      }
      if (other.hasRequestWithList()) {
        mergeRequestWithList(other.getRequestWithList());
      }
      if (requestListBuilder_ == null) {
        if (!other.requestList_.isEmpty()) {
          if (requestList_.isEmpty()) {
            requestList_ = other.requestList_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureRequestListIsMutable();
            requestList_.addAll(other.requestList_);
          }
          onChanged();
        }
      } else {
        if (!other.requestList_.isEmpty()) {
          if (requestListBuilder_.isEmpty()) {
            requestListBuilder_.dispose();
            requestListBuilder_ = null;
            requestList_ = other.requestList_;
            bitField0_ = (bitField0_ & ~0x00000008);
            requestListBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRequestListFieldBuilder() : null;
          } else {
            requestListBuilder_.addAllMessages(other.requestList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private io.siddhi.extension.map.protobuf.grpc.Request request_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.siddhi.extension.map.protobuf.grpc.Request, io.siddhi.extension.map.protobuf.grpc.Request.Builder, io.siddhi.extension.map.protobuf.grpc.RequestOrBuilder> requestBuilder_;
    /**
     * <code>.Request request = 1;</code>
     */
    public boolean hasRequest() {
      return requestBuilder_ != null || request_ != null;
    }
    /**
     * <code>.Request request = 1;</code>
     */
    public io.siddhi.extension.map.protobuf.grpc.Request getRequest() {
      if (requestBuilder_ == null) {
        return request_ == null ? io.siddhi.extension.map.protobuf.grpc.Request.getDefaultInstance() : request_;
      } else {
        return requestBuilder_.getMessage();
      }
    }
    /**
     * <code>.Request request = 1;</code>
     */
    public Builder setRequest(io.siddhi.extension.map.protobuf.grpc.Request value) {
      if (requestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        requestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Request request = 1;</code>
     */
    public Builder setRequest(
        io.siddhi.extension.map.protobuf.grpc.Request.Builder builderForValue) {
      if (requestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        requestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Request request = 1;</code>
     */
    public Builder mergeRequest(io.siddhi.extension.map.protobuf.grpc.Request value) {
      if (requestBuilder_ == null) {
        if (request_ != null) {
          request_ =
            io.siddhi.extension.map.protobuf.grpc.Request.newBuilder(request_).mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        requestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Request request = 1;</code>
     */
    public Builder clearRequest() {
      if (requestBuilder_ == null) {
        request_ = null;
        onChanged();
      } else {
        request_ = null;
        requestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Request request = 1;</code>
     */
    public io.siddhi.extension.map.protobuf.grpc.Request.Builder getRequestBuilder() {

      onChanged();
      return getRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.Request request = 1;</code>
     */
    public io.siddhi.extension.map.protobuf.grpc.RequestOrBuilder getRequestOrBuilder() {
      if (requestBuilder_ != null) {
        return requestBuilder_.getMessageOrBuilder();
      } else {
        return request_ == null ?
            io.siddhi.extension.map.protobuf.grpc.Request.getDefaultInstance() : request_;
      }
    }
    /**
     * <code>.Request request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.siddhi.extension.map.protobuf.grpc.Request, io.siddhi.extension.map.protobuf.grpc.Request.Builder, io.siddhi.extension.map.protobuf.grpc.RequestOrBuilder>
        getRequestFieldBuilder() {
      if (requestBuilder_ == null) {
        requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.siddhi.extension.map.protobuf.grpc.Request, io.siddhi.extension.map.protobuf.grpc.Request.Builder, io.siddhi.extension.map.protobuf.grpc.RequestOrBuilder>(
                getRequest(),
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      return requestBuilder_;
    }

    private io.siddhi.extension.map.protobuf.grpc.RequestWithMap requestWithMap_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.siddhi.extension.map.protobuf.grpc.RequestWithMap, io.siddhi.extension.map.protobuf.grpc.RequestWithMap.Builder, io.siddhi.extension.map.protobuf.grpc.RequestWithMapOrBuilder> requestWithMapBuilder_;
    /**
     * <code>.RequestWithMap requestWithMap = 2;</code>
     */
    public boolean hasRequestWithMap() {
      return requestWithMapBuilder_ != null || requestWithMap_ != null;
    }
    /**
     * <code>.RequestWithMap requestWithMap = 2;</code>
     */
    public io.siddhi.extension.map.protobuf.grpc.RequestWithMap getRequestWithMap() {
      if (requestWithMapBuilder_ == null) {
        return requestWithMap_ == null ? io.siddhi.extension.map.protobuf.grpc.RequestWithMap.getDefaultInstance() : requestWithMap_;
      } else {
        return requestWithMapBuilder_.getMessage();
      }
    }
    /**
     * <code>.RequestWithMap requestWithMap = 2;</code>
     */
    public Builder setRequestWithMap(io.siddhi.extension.map.protobuf.grpc.RequestWithMap value) {
      if (requestWithMapBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestWithMap_ = value;
        onChanged();
      } else {
        requestWithMapBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.RequestWithMap requestWithMap = 2;</code>
     */
    public Builder setRequestWithMap(
        io.siddhi.extension.map.protobuf.grpc.RequestWithMap.Builder builderForValue) {
      if (requestWithMapBuilder_ == null) {
        requestWithMap_ = builderForValue.build();
        onChanged();
      } else {
        requestWithMapBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.RequestWithMap requestWithMap = 2;</code>
     */
    public Builder mergeRequestWithMap(io.siddhi.extension.map.protobuf.grpc.RequestWithMap value) {
      if (requestWithMapBuilder_ == null) {
        if (requestWithMap_ != null) {
          requestWithMap_ =
            io.siddhi.extension.map.protobuf.grpc.RequestWithMap.newBuilder(requestWithMap_).mergeFrom(value).buildPartial();
        } else {
          requestWithMap_ = value;
        }
        onChanged();
      } else {
        requestWithMapBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.RequestWithMap requestWithMap = 2;</code>
     */
    public Builder clearRequestWithMap() {
      if (requestWithMapBuilder_ == null) {
        requestWithMap_ = null;
        onChanged();
      } else {
        requestWithMap_ = null;
        requestWithMapBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.RequestWithMap requestWithMap = 2;</code>
     */
    public io.siddhi.extension.map.protobuf.grpc.RequestWithMap.Builder getRequestWithMapBuilder() {

      onChanged();
      return getRequestWithMapFieldBuilder().getBuilder();
    }
    /**
     * <code>.RequestWithMap requestWithMap = 2;</code>
     */
    public io.siddhi.extension.map.protobuf.grpc.RequestWithMapOrBuilder getRequestWithMapOrBuilder() {
      if (requestWithMapBuilder_ != null) {
        return requestWithMapBuilder_.getMessageOrBuilder();
      } else {
        return requestWithMap_ == null ?
            io.siddhi.extension.map.protobuf.grpc.RequestWithMap.getDefaultInstance() : requestWithMap_;
      }
    }
    /**
     * <code>.RequestWithMap requestWithMap = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.siddhi.extension.map.protobuf.grpc.RequestWithMap, io.siddhi.extension.map.protobuf.grpc.RequestWithMap.Builder, io.siddhi.extension.map.protobuf.grpc.RequestWithMapOrBuilder>
        getRequestWithMapFieldBuilder() {
      if (requestWithMapBuilder_ == null) {
        requestWithMapBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.siddhi.extension.map.protobuf.grpc.RequestWithMap, io.siddhi.extension.map.protobuf.grpc.RequestWithMap.Builder, io.siddhi.extension.map.protobuf.grpc.RequestWithMapOrBuilder>(
                getRequestWithMap(),
                getParentForChildren(),
                isClean());
        requestWithMap_ = null;
      }
      return requestWithMapBuilder_;
    }

    private io.siddhi.extension.map.protobuf.grpc.RequestWithList requestWithList_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.siddhi.extension.map.protobuf.grpc.RequestWithList, io.siddhi.extension.map.protobuf.grpc.RequestWithList.Builder, io.siddhi.extension.map.protobuf.grpc.RequestWithListOrBuilder> requestWithListBuilder_;
    /**
     * <code>.RequestWithList requestWithList = 3;</code>
     */
    public boolean hasRequestWithList() {
      return requestWithListBuilder_ != null || requestWithList_ != null;
    }
    /**
     * <code>.RequestWithList requestWithList = 3;</code>
     */
    public io.siddhi.extension.map.protobuf.grpc.RequestWithList getRequestWithList() {
      if (requestWithListBuilder_ == null) {
        return requestWithList_ == null ? io.siddhi.extension.map.protobuf.grpc.RequestWithList.getDefaultInstance() : requestWithList_;
      } else {
        return requestWithListBuilder_.getMessage();
      }
    }
    /**
     * <code>.RequestWithList requestWithList = 3;</code>
     */
    public Builder setRequestWithList(io.siddhi.extension.map.protobuf.grpc.RequestWithList value) {
      if (requestWithListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestWithList_ = value;
        onChanged();
      } else {
        requestWithListBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.RequestWithList requestWithList = 3;</code>
     */
    public Builder setRequestWithList(
        io.siddhi.extension.map.protobuf.grpc.RequestWithList.Builder builderForValue) {
      if (requestWithListBuilder_ == null) {
        requestWithList_ = builderForValue.build();
        onChanged();
      } else {
        requestWithListBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.RequestWithList requestWithList = 3;</code>
     */
    public Builder mergeRequestWithList(io.siddhi.extension.map.protobuf.grpc.RequestWithList value) {
      if (requestWithListBuilder_ == null) {
        if (requestWithList_ != null) {
          requestWithList_ =
            io.siddhi.extension.map.protobuf.grpc.RequestWithList.newBuilder(requestWithList_).mergeFrom(value).buildPartial();
        } else {
          requestWithList_ = value;
        }
        onChanged();
      } else {
        requestWithListBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.RequestWithList requestWithList = 3;</code>
     */
    public Builder clearRequestWithList() {
      if (requestWithListBuilder_ == null) {
        requestWithList_ = null;
        onChanged();
      } else {
        requestWithList_ = null;
        requestWithListBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.RequestWithList requestWithList = 3;</code>
     */
    public io.siddhi.extension.map.protobuf.grpc.RequestWithList.Builder getRequestWithListBuilder() {

      onChanged();
      return getRequestWithListFieldBuilder().getBuilder();
    }
    /**
     * <code>.RequestWithList requestWithList = 3;</code>
     */
    public io.siddhi.extension.map.protobuf.grpc.RequestWithListOrBuilder getRequestWithListOrBuilder() {
      if (requestWithListBuilder_ != null) {
        return requestWithListBuilder_.getMessageOrBuilder();
      } else {
        return requestWithList_ == null ?
            io.siddhi.extension.map.protobuf.grpc.RequestWithList.getDefaultInstance() : requestWithList_;
      }
    }
    /**
     * <code>.RequestWithList requestWithList = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.siddhi.extension.map.protobuf.grpc.RequestWithList, io.siddhi.extension.map.protobuf.grpc.RequestWithList.Builder, io.siddhi.extension.map.protobuf.grpc.RequestWithListOrBuilder>
        getRequestWithListFieldBuilder() {
      if (requestWithListBuilder_ == null) {
        requestWithListBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.siddhi.extension.map.protobuf.grpc.RequestWithList, io.siddhi.extension.map.protobuf.grpc.RequestWithList.Builder, io.siddhi.extension.map.protobuf.grpc.RequestWithListOrBuilder>(
                getRequestWithList(),
                getParentForChildren(),
                isClean());
        requestWithList_ = null;
      }
      return requestWithListBuilder_;
    }

    private java.util.List<Request> requestList_ =
      java.util.Collections.emptyList();
    private void ensureRequestListIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        requestList_ = new java.util.ArrayList<Request>(requestList_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.siddhi.extension.map.protobuf.grpc.Request, io.siddhi.extension.map.protobuf.grpc.Request.Builder, io.siddhi.extension.map.protobuf.grpc.RequestOrBuilder> requestListBuilder_;

    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public java.util.List<Request> getRequestListList() {
      if (requestListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(requestList_);
      } else {
        return requestListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public int getRequestListCount() {
      if (requestListBuilder_ == null) {
        return requestList_.size();
      } else {
        return requestListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public io.siddhi.extension.map.protobuf.grpc.Request getRequestList(int index) {
      if (requestListBuilder_ == null) {
        return requestList_.get(index);
      } else {
        return requestListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public Builder setRequestList(
        int index, io.siddhi.extension.map.protobuf.grpc.Request value) {
      if (requestListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRequestListIsMutable();
        requestList_.set(index, value);
        onChanged();
      } else {
        requestListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public Builder setRequestList(
        int index, io.siddhi.extension.map.protobuf.grpc.Request.Builder builderForValue) {
      if (requestListBuilder_ == null) {
        ensureRequestListIsMutable();
        requestList_.set(index, builderForValue.build());
        onChanged();
      } else {
        requestListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public Builder addRequestList(io.siddhi.extension.map.protobuf.grpc.Request value) {
      if (requestListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRequestListIsMutable();
        requestList_.add(value);
        onChanged();
      } else {
        requestListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public Builder addRequestList(
        int index, io.siddhi.extension.map.protobuf.grpc.Request value) {
      if (requestListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRequestListIsMutable();
        requestList_.add(index, value);
        onChanged();
      } else {
        requestListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public Builder addRequestList(
        io.siddhi.extension.map.protobuf.grpc.Request.Builder builderForValue) {
      if (requestListBuilder_ == null) {
        ensureRequestListIsMutable();
        requestList_.add(builderForValue.build());
        onChanged();
      } else {
        requestListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public Builder addRequestList(
        int index, io.siddhi.extension.map.protobuf.grpc.Request.Builder builderForValue) {
      if (requestListBuilder_ == null) {
        ensureRequestListIsMutable();
        requestList_.add(index, builderForValue.build());
        onChanged();
      } else {
        requestListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public Builder addAllRequestList(
        Iterable<? extends Request> values) {
      if (requestListBuilder_ == null) {
        ensureRequestListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, requestList_);
        onChanged();
      } else {
        requestListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public Builder clearRequestList() {
      if (requestListBuilder_ == null) {
        requestList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        requestListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public Builder removeRequestList(int index) {
      if (requestListBuilder_ == null) {
        ensureRequestListIsMutable();
        requestList_.remove(index);
        onChanged();
      } else {
        requestListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public io.siddhi.extension.map.protobuf.grpc.Request.Builder getRequestListBuilder(
        int index) {
      return getRequestListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public io.siddhi.extension.map.protobuf.grpc.RequestOrBuilder getRequestListOrBuilder(
        int index) {
      if (requestListBuilder_ == null) {
        return requestList_.get(index);  } else {
        return requestListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public java.util.List<? extends RequestOrBuilder>
         getRequestListOrBuilderList() {
      if (requestListBuilder_ != null) {
        return requestListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(requestList_);
      }
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public io.siddhi.extension.map.protobuf.grpc.Request.Builder addRequestListBuilder() {
      return getRequestListFieldBuilder().addBuilder(
          io.siddhi.extension.map.protobuf.grpc.Request.getDefaultInstance());
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public io.siddhi.extension.map.protobuf.grpc.Request.Builder addRequestListBuilder(
        int index) {
      return getRequestListFieldBuilder().addBuilder(
          index, io.siddhi.extension.map.protobuf.grpc.Request.getDefaultInstance());
    }
    /**
     * <code>repeated .Request requestList = 4;</code>
     */
    public java.util.List<Request.Builder>
         getRequestListBuilderList() {
      return getRequestListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.siddhi.extension.map.protobuf.grpc.Request, io.siddhi.extension.map.protobuf.grpc.Request.Builder, io.siddhi.extension.map.protobuf.grpc.RequestOrBuilder>
        getRequestListFieldBuilder() {
      if (requestListBuilder_ == null) {
        requestListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.siddhi.extension.map.protobuf.grpc.Request, io.siddhi.extension.map.protobuf.grpc.Request.Builder, io.siddhi.extension.map.protobuf.grpc.RequestOrBuilder>(
                requestList_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        requestList_ = null;
      }
      return requestListBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:OtherMessageTypes)
  }

  // @@protoc_insertion_point(class_scope:OtherMessageTypes)
  private static final io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes();
  }

  public static io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OtherMessageTypes>
      PARSER = new com.google.protobuf.AbstractParser<OtherMessageTypes>() {
    @Override
    public OtherMessageTypes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OtherMessageTypes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OtherMessageTypes> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<OtherMessageTypes> getParserForType() {
    return PARSER;
  }

  @Override
  public io.siddhi.extension.map.protobuf.grpc.OtherMessageTypes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

