// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package io.siddhi.extension.map.protobuf.grpc;

public interface ResponseWithListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseWithList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string stringList = 1;</code>
   */
  java.util.List<String>
      getStringListList();
  /**
   * <code>repeated string stringList = 1;</code>
   */
  int getStringListCount();
  /**
   * <code>repeated string stringList = 1;</code>
   */
  String getStringList(int index);
  /**
   * <code>repeated string stringList = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringListBytes(int index);

  /**
   * <code>repeated int32 intList = 2;</code>
   */
  java.util.List<Integer> getIntListList();
  /**
   * <code>repeated int32 intList = 2;</code>
   */
  int getIntListCount();
  /**
   * <code>repeated int32 intList = 2;</code>
   */
  int getIntList(int index);
}
